/**
 * Base Component React Native App
 *
 * @author
 * tera - https://github.com/teukuraja
 * facebook - https://github.com/facebook/react-native
 *
 * https://github.com/teukuraja/teraRNBoilerPlate
 *
 * @format
 * @flow strict-local
 *
 * WARNING!!!
 * 1) DO NOT EDIT THIS FILE UNLESS YOU NEED ADDITIONAL CONFIGURATION OF THIS PROJECT
 * 2) DO NOT RENAME OR MOVE THIS FILE
 * 3) READ THE README FILE TO USE THIS TEMPLATE
 */

import React from 'react';
import { SafeAreaView, ActivityIndicator } from 'react-native';
import { Provider as StoreProvider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import 'react-native-gesture-handler';
import { I18nextProvider } from 'react-i18next';
import { AppStatusBar } from '../Components';
import { getPersistor, getStore } from '../Redux/Store';
import RootNavigation from './Navigation.config';
import { Colors } from '../Themes';
import I18n from '../I18n/I18n';

const store = getStore();
const persistor = getPersistor();

const COLOR_THEME = Colors.AUBERGINE;

const Style = (flex: number) => ({ flex: flex, backgroundColor: COLOR_THEME });

const BaseApp: () => React$Node = () => (
  <I18nextProvider i18n={I18n}>
    <SafeAreaView style={Style(0)} />
    <SafeAreaView style={Style(1)}>
      <AppStatusBar backgroundColor={COLOR_THEME} barStyle="light-content" />
      <StoreProvider store={store}>
        <PersistGate loading={<ActivityIndicator />} persistor={persistor}>
          <RootNavigation />
        </PersistGate>
      </StoreProvider>
    </SafeAreaView>
  </I18nextProvider>
);

export default BaseApp;
